### ISSUE TITLE
Fix: Run Undercover silently failing when running Danger in CI

### ISSUE THREAD

**Issue by htoo-eain-lwin** [nimblehq/rails-templates#454]
## Issue

It's only happening when the repo name includes `-`. It'll work if the repo name is single word or use `_`.

<img width="1331" alt="Screenshot 2023-08-03 at 16 15 28" src="https://github.com/nimblehq/rails-templates/assets/4177116/35ed75b8-a965-4d36-971a-4acc723127ac">
As you see, even tough it's showing the error, our `Run Danger` is still passing.

```
/home/runner/work/google-crawler/google-crawler/vendor/bundle/ruby/3.2.0/gems/undercover-0.4.6/lib/
undercover.rb:32:in `initialize': No such file or directory @ rb_sysopen - /home/runner/work/
google-crawler/google-crawler/coverage/lcov/google-crawler.lcov (Errno::ENOENT)
	from /home/runner/work/google-crawler/google-crawler/vendor/bundle/ruby/3.2.0/gems
	/undercover-0.4.6/lib/undercover.rb:32:in `open'
```
I think this happens when undercover-report tries to find `/lcov/google-crawler.lcov` instead of `/lcov/google_crawler.lcov` 

<img width="916" alt="Screenshot 2023-08-03 at 16 21 20" src="https://github.com/nimblehq/rails-templates/assets/4177116/f1dd38fe-b80e-4c12-90d9-59328504c753">

But it's creating correctly `lcov/google-crawler.lcov` when try to run in local 😵 
![Screenshot 2023-08-03 at 16 32 27](https://github.com/nimblehq/rails-templates/assets/4177116/0aa9c71a-cafc-499f-953a-e41c0e9af469)

## Expected

```
Run bundle exec undercover-report -l /home/runner/work/google-crawler/google-crawler/coverage/lcov/google_crawler.lcov
##[debug]/usr/bin/bash -e /home/runner/work/_temp/ba524503-14d3-42fe-bd4b-8148a20b0d53.sh
✅ No reportable changes
Undercover finished in 0.015s
```

## Steps to reproduce

1.  Create New project using our template, make sure to include `-` in the repo name and  create pull request to main or  develop with some changes.
2. You can see the error under `Run Danger` > `Run Undercover`

**Comment by htoo-eain-lwin** [comment]
For now, I can by pass via updating to the following in the `test.yml`
```
  - name: Run Undercover
    run: bundle exec undercover-report -l /home/runner/work/google-crawler/google-crawler/coverage/lcov/google_crawler.lcov
```
